### ISSUE TITLE
CI/CD: Switch to lightweight Kubernetes distribution

### ISSUE THREAD

**Issue by armab** [StackStorm/stackstorm-k8s#243]
Currently, we're relying on CircleCI large container size that provides 4CPUs & 15GB RAM ~which is a paid feature~ (Update: it's free now):
https://github.com/StackStorm/stackstorm-ha/blob/3ba85e6c584229e21cf41e2d19ec14f2bef4ffcc/.circleci/config.yml#L52-L55

1) Switch to a smaller CircleCI container size
2) Replace K8s with a lightweight distribution like K3s or K0s that'll fit CI/CD environment better:
- https://k3s.io/
- https://github.com/k0sproject/k0s/
- https://kind.sigs.k8s.io/

~Hopefully, this could also help with the issues when builds reported random stability failures caused by etcd/K8s/CircleCI~ (Update: it runs well recently).

**Comment by cognifloyd** [comment]
This looks like a good way to run k3s in Github Actions: https://github.com/marketplace/actions/actions-k3s

**Comment by cognifloyd** [comment]
Or this for kind: https://github.com/marketplace/actions/kind-cluster
