### ISSUE TITLE
Support for Kubernetes 1.22 - networking.k8s.io/v1beta1 removed

### ISSUE THREAD

**Issue by agateblue** [StackStorm/stackstorm-k8s#277]
Several APIs where deprecated in Kubernetes 1.22, in particular the `networking.k8s.io/v1beta1` (used [here](https://github.com/StackStorm/stackstorm-ha/blob/7d55c4964ef33893e042ba84e1756f1650172d39/templates/ingress.yaml#L3)). This prevent `ingress.yaml` to deploy successfully on Kubernetes 1.22.

I think it could be possible to support both APIs, using conditional logic ([Grafana does this](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_helpers.tpl#L132-L163), for example).

**Comment by armab** [comment]
That's a nice hack :+1: 

Sure, a PR would be welcome to support it!

**Comment by arms11** [comment]
FYI, I have raised a [PR](https://github.com/StackStorm/stackstorm-k8s/pull/301) for this as `EKS` just announced support of the `v.1.22`. We will need to use this change for our production upgrade and will test it out soon.
