### ISSUE TITLE
Overrides for Rules/Sensors 

### ISSUE THREAD

**Issue by cwilson21** [StackStorm/stackstorm-k8s#306]
I have 2 stackstorm instances running out of the same repo with packs etc. I have rules that I do not want to be enabled however on the `dev` instance but need to be enabled on the `prod` instance. Looking at some recent PRs from the `st2` repo I see that there is functionality in base stackstorm to make overrides however you rely on the directory `/opt/stackstorm/config/overrides/` existing and in the k8s version we are not able to find this directory and are not sure how to specify in our charts to disable rules using this method. 

If this is already useable just an explanation of how it can be used now if not can this be added so it is able to be used?

**Comment by armab** [comment]
You can do that now via `extra_volumes` so you'll mount override files under the `/opt/stackstorm/config/overrides/`.
Example: https://github.com/StackStorm/stackstorm-k8s/blob/master/values.yaml#L646-L678

But ideally, for a native UX, someone needs to implement the feature so it's easily configurable via Helm `values.yaml`, similar to RBAC: https://github.com/StackStorm/stackstorm-k8s/blob/master/values.yaml#L200-L236

**Comment by cwilson21** [comment]
Interesting, just looking this might be one that I can add. I am going to fork this and play with it to see if I can get it working and if I do I will make a Pull Request.

**Comment by cognifloyd** [comment]
If you work on this, please use `/opt/stackstorm/overrides` (without `/config` - that was in one of the WIP PRs, but it was changed to drop it before merging).

**Comment by cwilson21** [comment]
So I think I have gotten this added. I am doing some testing locally to make sure functionality is in place and if it is I will make a pull request.

**Comment by cwilson21** [comment]
So this was fairly easy to configure and setup, however I am having one issue. I have added this to `st2client` and configs do not get overridden on build (`st2ctl reload` enforces the overrides) , but is expected because all of that is loaded in with the `register` job. However when trying to put this through the `register` job I am not having success getting things to load. Looking at `st2-register-content` I am not sure if this actually processes overrides, maybe @cognifloyd can give more insight on this.

**Comment by cwilson21** [comment]
PR created https://github.com/StackStorm/stackstorm-k8s/pull/307
