### ISSUE TITLE
Problem with pvc volume mount on job-st2-register-content

### ISSUE THREAD

**Issue by krgaurav1287** [StackStorm/stackstorm-k8s#320]
I am new to stackstrom trying to use volume mount in order to enable write option using pvc.

Always get job-st2-register-content keeps on waiting to start.
  I referred issue 238 which was having similar issue but with NFS deploy.

Any help is much appreciated. Thanks!!

**Comment by krgaurav1287** [comment]
@cognifloyd  I show your response on that issue is it something you can help me here please.

**Comment by cognifloyd** [comment]
If it is waiting to start, then the volume you requested might not be available.
Please create your volume outside of the chart, and load it in a one-off test-pod.
That will ensure that you've got all of the volume details before you worry about anything else in the chart.

Also, please ensure that your volume allows RWX (Read Write Many).

**Comment by cognifloyd** [comment]
Do you have `jobs.preRegisterContentCommand` defined in your values?

**Comment by krgaurav1287** [comment]
Thanks a lot!!
Currently I am using chart version v0.80.0

How can I accommodate this changes in v.0.80.0

**Comment by krgaurav1287** [comment]
Hello @cognifloyd, will I be able to make this changes in version v0.80.0

**Comment by cognifloyd** [comment]
I don't know if the issue I identified is your issue. Do you have `jobs.preRegisterContentCommand` defined?

**Comment by krgaurav1287** [comment]
Thanks for looking into it!!  
If you get any idea from below input to start troubleshooting please advice. 
**kubectl logs st2-job-st2-register-content-h7rzc -n st2**
Defaulted container "st2-register-content" out of: st2-register-content, wait-for-db (init), st2-custom-pack-36bd025aa9330455f1480e399bff0a4fbede794f (init), st2-system-packs (init), st2-pack-configs-from-helm (init), st2-register-content-custom-init (init)
Error from server (BadRequest): container "st2-register-content" in pod "st2uat-job-st2-register-content-h7rzc" is waiting to start: PodInitializing

**Comment by cognifloyd** [comment]
Do the logs for those init containers show anything?

**Comment by krgaurav1287** [comment]
No it doesn't show anything but one major difference I can see is, when I volume is not enabled the file created under /opt/stackstorm/packs 
/opt/stackstorm/virtualenvs

File ownership shows 
root st2packs
But when we enable volume 
File ownership shows 
root root

**Comment by krgaurav1287** [comment]
@elsopapa is this something you can help me

**Comment by rebrowning** [comment]
Hopping on here, I created a PR that I'm able to use to deploy successfully on a minikube instance with volumes attached.
PR: https://github.com/StackStorm/stackstorm-k8s/pull/324
