### ISSUE TITLE
Actions failing because Python missing libraries

### ISSUE THREAD

**Issue by usulkies** [StackStorm/stackstorm-k8s#334]
I'm struggling to understand what could be the reason I'm getting this error for every action starting to run.
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f7c75542740 (most recent call first):
```

This has started happening without a clear reason, after I updated the helm values.
I feel I'm not sure enough how to debug this.
Should the basic libraries like "encodings" should be inside the virutalenv of each package? Or should they reside under /usr/lib/python3.8/ like they do?
This error is happening on st2workflowengine pods when starting a workflow, and also on st2sensorcontainer when just running an action like aws.acm_list_certificates.

**Comment by denis-rodionov** [comment]
The same issue after updating image version from 3.6 to 3.7

**Comment by usulkies** [comment]
I gave up eventually and created a shared volume so now I can install packs from the web or the client.
I assume that something is not working properly with the image creation. The virtual environment is not created as it should

**Comment by denis-rodionov** [comment]
I also solved it: in my case the problem was in a pack image, which had a different version (3.6) and that caused a mess in pack virtual environment and led to such errors.
