### ISSUE TITLE
ingressClassName field missing 

### ISSUE THREAD

**Issue by ciechonp** [StackStorm/stackstorm-k8s#336]
As of Kubernetes 1.18 ingressClassName field was added. kubernetes.io/ingress.class is now deprecated. 
https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
Can Ingress definition in this chart be updated to include ingressClassName field?

**Comment by armab** [comment]
Thanks for the report 👍 
A PR contribution would be helpful to support this.
