### ISSUE TITLE
Error "found duplicate key headers" from aws pack when running v0.110.0

### ISSUE THREAD

**Issue by lordpengwin** [StackStorm/stackstorm-k8s#362]
I'm trying to install v0.110.0 and it is failing with  the following error:

`Failed to register actions: Failed to register action "/opt/stackstorm/packs/aws/actions/apigateway_test_invoke_authorizer.yaml" from pack "aws": found duplicate key "headers"`

I've found a reference to this here: https://github.com/StackStorm/community/issues/81 but i don't see a resolution or work around.

**Comment by guzzijones** [comment]
It looks like the pack config or the apigateway_test_invoke_authorizer.yaml file has duplicate fields.  This was fixed in a recent version of st2 to NOT allow duplicates.
