### ISSUE TITLE
st2clientConfig issue with jobs.extra_hooks

### ISSUE THREAD

**Issue by cars** [StackStorm/stackstorm-k8s#370]
We're trying to use extra_hooks in a k8s deployment and running into an issue where the additional jobs we define get run. But we find as we try to run additional st2 commands that we're seeing an error along the lines of: 

`configparser.DuplicateSectionError: While reading from '/root/.st2/config' [line 2]: section 'credentials' already exists`

In looking into this issue I see that at https://github.com/StackStorm/stackstorm-k8s/blob/415e3a672517762e747f446a13697464df210830/values.yaml#L925-L928 creating a st2clientConfig value that `[credentials]` is included in the config value. 
But in the jobs template '[credentials]' is being pre-prended to the st2clientConfig value: https://github.com/StackStorm/stackstorm-k8s/blob/415e3a672517762e747f446a13697464df210830/templates/jobs.yaml#L663-L666

resulting in a config file that looks like: 

```
[credentials]
[credentials]
username=st2admin
password=fred
```

**Comment by armab** [comment]
Good find!
