### ISSUE TITLE
sendmail configuration is impossible inside a container

### ISSUE THREAD

**Issue by guzzijones** [StackStorm/stackstorm-k8s#373]
sendmail needs to run a daemon locally which is not possible inside a container. 
attempting to use sendmail inside a container results in 
```
connection refused 127.0.0.1
```

sendmail apparently runs a local MTA as a service.  It is not possible to run this service in a container.

The common solution I see is to use[ ssmtp ](https://www.michelebologna.net/2019/send-an-email-from-a-docker-container/)

There are no ssmtp packages supported for rocky 8 or 9.

Has anyone successfully gotten sendmail to connect to an external MTA?  
I attempted setting SMART_HOST and recompiling the sendmail.cf, but it still connects to localhost hen i run sendmail inside the container.

**Comment by guzzijones** [comment]
I actually managed to get my own container build to work by changing sendmail.mc config with:
```
define(`SMART_HOST', `hostname_not_mx.tld')dnl
define(`nullclient', `hostname_not_mx.tld')dnl
```
then running 
```
buildah copy "$container" sendmail.mc /etc/mail/sendmail.mc
buildah run "$container" bash -c "bash /etc/mail/make"
buildah run "$container" bash -c "sendmail -bd"
```

but this isn't possible with the st2 container since the sendmail.mc config file needs to be changed and rebuilt

**Comment by guzzijones** [comment]
In the end ssmtp is [infinitly easier to setup iwith a config file ](https://www.atlantic.net/vps-hosting/how-to-use-ssmtp-to-send-an-email-from-linux-terminal/)

**Comment by sburlappp** [comment]
I agree, I made the same recommendation elsewhere, and it works well for me:

https://github.com/StackStorm/st2/issues/6002

**Comment by guzzijones** [comment]
it turns out `ssmtp` does NOT work with piped input with `TO:` in the input file.  `ssmtp` requires an to address via command line
```
bash-4.4# cat mail | ssmtp
sendmail: No recipients supplied - mail will not be sent

```
so i ended up writing a new action instead of using sendmail and overriding the binary.

**Comment by guzzijones** [comment]
```
/usr/sbin/sendmail -t 
```
should work with the send_mail action
`-t` tells it to use the TO from the input file.   Why they did that I have no idea.  Probably some old rfc specification.
