### ISSUE TITLE
Not able to create new action in stackstorm (which is deployed on K8s in docker desktop) 

### ISSUE THREAD

**Issue by axl-ankush** [StackStorm/stackstorm-k8s#380]
{
  "error": "[Errno 2] No such file or directory: '/opt/stackstorm/packs/default/actions/workflows/Action_test.yaml'",
  "traceback": "  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/st2actions/container/base.py\", line 132, in _do_run
    (status, result, context) = runner.run(action_params)
  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/orquesta_runner/orquesta_runner.py\", line 125, in run
    return self.start_workflow(action_parameters)
  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/orquesta_runner/orquesta_runner.py\", line 129, in start_workflow
    wf_def = self.get_workflow_definition(self.entry_point)
  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/orquesta_runner/orquesta_runner.py\", line 49, in get_workflow_definition
    with open(entry_point, \"r\") as def_file:
"
}   

getting the above error when I am trying to run the new workflow using the default actions like core.local

**Comment by arms11** [comment]
You are trying to test something on Docker Desktop based single node Kubernetes cluster. Does your setup takes into the account of the docker image for the pack where the `Action_test.yaml` is kept? 
`[Errno 2] No such file or directory: '/opt/stackstorm/packs/default/actions/workflows/Action_test.yaml` makes me believe the pack does not have this file or that it is not registered successfully.

**Comment by axl-ankush** [comment]
Thanks @arms11 for helping, I have resolved the issue, dockerfile was not able to copy the path correctly but
