### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by bmarick** [StackStorm/stackstorm-k8s#384]
Hello what does it take to release a new version of the chart?
My team would like to use features that are currently in main, but not in a release

**Comment by bmarick** [comment]
@guzzijones any chance you can take a look at this question?

**Comment by mamercad** [comment]
I believe the process is to update the `version` in [Chart.yaml](https://github.com/StackStorm/stackstorm-k8s/blob/master/Chart.yaml#L5) and push a matching tag. After which it'll eventually be discovered by [ArtifactHub](https://artifacthub.io/packages/helm/stackstorm/stackstorm-ha). Is that correct @arm4b ?

**Comment by arm4b** [comment]
@mamercad Yes, that's the first step.
Then you need to update the https://github.com/StackStorm/stackstorm-k8s/tree/gh-pages index with the new artifact.
I think the https://helm.sh/docs/helm/helm_repo_index/ command is how to do it.
Example: https://github.com/StackStorm/stackstorm-k8s/commit/82c4d565402a27205ed5fdbe3ded783e90786e5f

That could be automated.

**Comment by mamercad** [comment]
Maybe as a first pass at this, and, getting it out the door, we add "Releasing information" to the `README.md` with the steps and get the new version out with it. Are we ready for `v1.0.0` at this point?

**Comment by arm4b** [comment]
I know no barriers for `v1.0` and the chart is known to be used in production for a long time. @cognifloyd WDYT ?

**Comment by guzzijones** [comment]
This chart is in good shape now.

**Comment by mamercad** [comment]
I've deployed [chart-releaser](https://github.com/helm/chart-releaser) for another project in the past, might be worthwhile for this one as well; I'll snag this issue.

**Comment by mamercad** [comment]
@arm4b 👀 when you have a chance, please.

**Comment by mamercad** [comment]
...we may want to think about an organizational GPG key for signing.

**Comment by bmarick** [comment]
So a question if you are going to do a version 1 should we consider upgrading the Mongo, RabbitMQ and Redis Helm Charts?
There are some breaking changes in those.

**Comment by mamercad** [comment]
> So a question if you are going to do a version 1 should we consider upgrading the Mongo, RabbitMQ and Redis Helm Charts? There are some breaking changes in those.

I think (I don't have anything other than anecdotal information to back this up) that folks have been running `main` for a while now? Changing "all of the other things" at this point should be a new issue and new work, I'd argue.
