### ISSUE TITLE
Deployments have labels that are redundant when existing secrets are provided.

### ISSUE THREAD

**Issue by bmarick** [StackStorm/stackstorm-k8s#393]
When providing an existing Auth or DataStore Key secret it generates a checksum of a file that is never needed.
Sense the file is not used, the checksum becomes a static value.
Additionally, this checksum is calculated multiple times.
This results in larger output templates and slower helm chart builds.
My suggestion is to remove them.

**Comment by cognifloyd** [comment]
I believe #391 and #392 implement this. If anything else is required, we can reopen or file a new issue.
